# Generated by Django 5.2.17 on 2026-09-24 16:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='soru')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='yazar')),
            ],
            options={
                'verbose_name': 'anket',
                'verbose_name_plural': 'anketler',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='seçenek')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll', verbose_name='anket')),
            ],
            options={
                'verbose_name': 'seçenek',
                'verbose_name_plural': 'seçenekler',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('poll', 'order'), name='unique_option_order_per_poll'), models.CheckConstraint(condition=models.Q(('order__lte', 4)), name='option_order_max_4')],
            },
        ),
    ]
