# Generated by Django 5.2.17 on 2026-09-24 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_token', models.CharField(blank=True, max_length=36, null=True, verbose_name='ziyaretçi anahtarı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oy zamanı')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option', verbose_name='seçenek')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll', verbose_name='anket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='üye')),
            ],
            options={
                'verbose_name': 'oy',
                'verbose_name_plural': 'oylar',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('poll', 'user'), name='unique_vote_per_user'), models.UniqueConstraint(condition=models.Q(('voter_token__isnull', False)), fields=('poll', 'voter_token'), name='unique_vote_per_token'), models.CheckConstraint(condition=models.Q(('user__isnull', False), ('voter_token__isnull', False), _connector='OR'), name='vote_has_user_or_token')],
            },
        ),
    ]
