# Generated by Django 5.2.17 on 2026-09-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='closes_at',
            field=models.DateTimeField(blank=True, help_text='Boşsa anket süresiz açık kalır.', null=True, verbose_name='oylama bitişi'),
        ),
    ]
