# Generated by Django 5.2.17 on 2026-09-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_closes_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(choices=[('gunluk', 'Günlük hayat'), ('yemek', 'Yemek & içecek'), ('alisveris', 'Alışveriş & moda'), ('eglence', 'Film, dizi & müzik'), ('seyahat', 'Seyahat'), ('teknoloji', 'Teknoloji'), ('iliskiler', 'İlişkiler'), ('kariyer', 'Okul & kariyer'), ('spor', 'Spor & sağlık'), ('diger', 'Diğer')], db_index=True, default='diger', max_length=20, verbose_name='kategori'),
        ),
    ]
