# Generated by Django 5.2.17 on 2026-09-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hız sınırı kaydı',
                'verbose_name_plural': 'hız sınırı kayıtları',
                'indexes': [models.Index(fields=['scope', 'key', 'created_at'], name='ratelimit_lookup')],
            },
        ),
    ]
