# Generated by Django 5.2.17 on 2026-09-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_ratelimithit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Gizli anketler akışta görünmez; sadece sahibi ve yöneticiler açabilir.', verbose_name='gizli'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='tarih')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, verbose_name='gizli')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='yazar')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='polls.poll', verbose_name='anket')),
            ],
            options={
                'verbose_name': 'yorum',
                'verbose_name_plural': 'yorumlar',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_token', models.CharField(max_length=36, verbose_name='ziyaretçi anahtarı')),
                ('reason', models.CharField(choices=[('spam', 'Spam / reklam'), ('hakaret', 'Hakaret veya nefret söylemi'), ('uygunsuz', 'Cinsel ya da uygunsuz içerik'), ('kisisel', 'Kişisel bilgi paylaşımı'), ('diger', 'Diğer')], max_length=20, verbose_name='sebep')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='tarih')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='incelendi')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='polls.poll', verbose_name='anket')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='şikayet eden')),
            ],
            options={
                'verbose_name': 'şikayet',
                'verbose_name_plural': 'şikayetler',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('poll', 'voter_token'), name='unique_report_per_browser'), models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('poll', 'reporter'), name='unique_report_per_user')],
            },
        ),
    ]
