# Generated by Django 5.2.17 on 2026-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_reports_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='görsel'),
        ),
    ]
